# Generated by Django 2.1.2 on 2018-12-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songupload',
            name='dijay',
        ),
    ]
