# Generated by Django 2.1.2 on 2018-12-04 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songr', '0002_remove_songupload_dijay'),
    ]

    operations = [
        migrations.AddField(
            model_name='songupload',
            name='dejay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
