# Generated by Django 2.1.2 on 2018-12-06 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songr', '0007_songupload_dejay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songupload',
            name='dejay',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
