# Generated by Django 2.1.2 on 2018-12-06 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songr', '0008_auto_20181206_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_file', models.FileField(null=True, upload_to='videos/', verbose_name='')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('dejay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='songupload',
            name='dejay',
        ),
        migrations.DeleteModel(
            name='SongUpload',
        ),
    ]
