# Generated by Django 2.1.2 on 2018-12-17 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('songr', '0010_auto_20181211_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickSong',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('interests', models.ManyToManyField(related_name='song_interests', to='songr.PlaylistUpload')),
            ],
        ),
    ]
