# Generated by Django 2.1.2 on 2018-12-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songr', '0011_picksong'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistupload',
            name='interests',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='PickSong',
        ),
    ]
