# Generated by Django 2.1.2 on 2018-12-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songr', '0012_auto_20181218_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistupload',
            name='interests',
            field=models.BooleanField(default=True),
        ),
    ]
