# Generated by Django 2.1.2 on 2018-12-19 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('songr', '0013_auto_20181218_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickSong',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='playlistupload',
            name='interests',
        ),
        migrations.AddField(
            model_name='picksong',
            name='interests',
            field=models.ManyToManyField(related_name='song_interests', to='songr.PlaylistUpload'),
        ),
    ]
